### ISSUE TITLE
Strange code in semigrp.cc

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/Semigroups#284]
semigrp.cc, line 1091, is:

```gap_rec_t fp = fropin(so, INTOBJ_INT(pos), 0, False);```

Something seems weird here, `pos` is `gap_int_t`, so already a pointer.

**Comment by james-d-mitchell** [comment]
@ChrisJefferson thanks! Well spotted! I guess this never caused an issue because the second parameter of the function `fropin` is the limit (i.e. the semigroup being enumerated is enumerated until `pos` many elements are found, or the enumeration is completed), so I guess that the `INTOBJ_INT(pos)` was usually large enough that the enumeration ran until the end. I think I've fixed this in PR #285.

**Comment by ChrisJefferson** [comment]
If you wonder how I ever wandered across this, I am working on turning various macros in GAP into functions, so they get typechecked (this was the only thing that came up in semigroups).

**Comment by james-d-mitchell** [comment]
Nice, I did wonder!
