### ISSUE TITLE
XClassReps

### ISSUE THREAD

**Issue by ChristopherRussell** [gap-packages/Semigroups#402]
```
gap> S := SymmetricInverseMonoid(4);;
gap> H := HClass(S, PartialPerm([1,2,3],[1,2,3]));;
gap> R := RClass(S, H);
<Green's R-class: <Green's H-class: <identity partial perm on [ 1, 2, 3 ]>>>
gap> HClassReps(R);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
The 1st argument is 'fail' which might point to an earlier problem
Error, no 1st choice method found for `GreensHClasses' on 1 arguments at /Users/crussell/gap/lib/methsel2.g:241 called from
GreensHClasses( CanonicalGreensClass( x ) ) at /Users/crussell/gap/lib/semirel.gi:721 called from
GreensHClasses( C ) at /Users/crussell/gap/pkg/semigroups/gap/greens/gree.gi:380 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:361
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
```

**Comment by wilfwilson** [comment]
According to the documentation, implicitly the line `gap> R := RClass(S, H);` should not have worked:

> Note  that  `GreensXClassOfElement` and `XClass` are synonyms and have identical output. The shorter command is provided for the sake of convenience.

Looking at the documentation, the correct command is `gap> R := RClassOfHClass(H);` or `gap> R := RClass(H);`, which give:
```
gap> S := SymmetricInverseMonoid(4);
<symmetric inverse monoid of degree 4>
gap> S := SymmetricInverseMonoid(4);;
gap> H := HClass(S, PartialPerm([1,2,3],[1,2,3]));;
gap> R := RClassOfHClass(H);
<Green's R-class: <identity partial perm on [ 1, 2, 3 ]>>
gap> HClassReps(R);
[ <identity partial perm on [ 1, 2, 3 ]>, [1,2,3,4], [2,4](1,3), [3,2,1,4] ]
```
Either we actually *want* to be able to do `RClass(S, H)`, and so the code should be updated to allow it, or the code should be updated so that `RClass(S, H)` gives 'no method found'. The documentation should be updated in either case, to emphasise the behaviour.

**Comment by james-d-mitchell** [comment]
`RClass(S, H)` should definitely not work, this is the bug.

**Comment by james-d-mitchell** [comment]
I think I fixed this in [GAP PR 1771](https://github.com/gap-system/gap/pull/1771). This prevents `RClass(S, H)` from working and hence prevents the other errors in this issue.
