### ISSUE TITLE
Occasional save-workspace diffs in Travis

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#542]
I've opened this issue to collect instances of Travis producing failures in the `save-workspace.tst` test. Here's one example from https://travis-ci.org/gap-packages/Semigroups/jobs/433946517#L4404
```
########> Diff in save-workspace.tst:155
# Input is:
SaveWorkspace(Concatenation(SEMIGROUPS.PackageDir,
                               "/tst/workspaces/test-output.w"));
# Expected output:
true
# But found:
#W bad bag id -1632527300 found, 0 saved
true
########
Semigroups package: workspaces/save-workspace.tst
msecs: 1220
false
```
Hopefully harmless, but we should work out what is happening and when. If it is harmless, then we should find a way to stop this from failing the Travis tests.

**Comment by james-d-mitchell** [comment]
Does this by any chance only occur in 32-bit builds? This is probably not harmless, it indicates that something in the workspace is not saved correctly (maybe because of some over/underflow issue), and it just so happens that that same thing is not used/accessed again in the loaded workspace.

**Comment by wilfwilson** [comment]
I can't be sure but I think I've only seen it in 32-bit builds. If we collect more instances of this, that should become apparent.

**Comment by wilfwilson** [comment]
Another instance: https://travis-ci.org/gap-packages/Semigroups/jobs/443211689

**Comment by wilfwilson** [comment]
Once a day, Travis now runs the tests on the latest commit of `stable-3.0`, and on the latest commit of `master` (if they have not been tested in the previous 24 hours). This will probably give us a better feeling for how often this is occurring.

**Comment by james-d-mitchell** [comment]
Good idea, @wilfwilson. Since I didn't explain before, I intend to resolve this issue by completely replacing the Semigroups kernel module at some point in the not too distant future. Depending on how much time I have this will be sooner or later, I'm not 100% sure when.

The idea is to write some generic (i.e. not related to the Semigroups package) code for interfacing between C++ and GAP, in the same vein as [pybind11](https://github.com/pybind/pybind11), and to just use this with Semigroups, instead of the mess that is there right now. 

I have a prototype for the interface, but it requires more work.

**Comment by wilfwilson** [comment]
Ah, that's good.

**Comment by wilfwilson** [comment]
https://travis-ci.org/gap-packages/Semigroups/jobs/458880975

**Comment by wilfwilson** [comment]
https://travis-ci.org/gap-packages/Semigroups/jobs/470676180

**Comment by wilfwilson** [comment]
Haven't seen one for a while.

**Comment by wilfwilson** [comment]
This hasn't happened for 3 months; the tests on the `master` and `stable` branches are run at least twice a day. I'll close the issue now, but re-open if I ever see it coming back.

**Comment by wilfwilson** [comment]
@ChrisJefferson has tracked down that cause of this, it's a GAP problem.
