### ISSUE TITLE
Un-vendor libsemigroup?

### ISSUE THREAD

**Issue by dimpase** [gap-packages/Semigroups#580]
Presently it appears that there is no way to tell the `semigroups` configure script that `libsemigroups` is already installed, and this causes problems if one tries out-of-tree installation of `semigroups` package, like we do in Sage (we are able to use other GAP kernel modules, just not this one).

A clean way out would be to allow using already installed `libsemigroups`, which is after all an ordinary C++ library.

Would be accept a PR to fix this? Thanks...

**Comment by james-d-mitchell** [comment]
Thanks @dimpase, yes of course we'd be happy to consider a PR.

**Comment by dimpase** [comment]
Why is there a check for the libsemigroup's version at all? Such a test, for a nested sub-package, makes sense when the tarball is made, not at every installation, no?

**Comment by james-d-mitchell** [comment]
There is a check because some people using the development version requested that `Semigroups` check that the correct version of `libsemigroups` is available. If you clone the `Semigroups` and `libsemigroups` repos, it is quite easy to get the wrong version of `libsemigroups`. 

You are right that it doesn't need to be checked in the release version, but at the same time, I can't see that it does any harm either. Anyway, it looks like this will be revised by your PR, no?

**Comment by dimpase** [comment]
Well, yes, the plan is that an external version of libsemigroup should be installed as a normal external library, then it's version is to be checked by standard tools.

So if an external version is not found or fails checks, then the internal version is used (but then one does not need to check its version).
(or perhaps libsemigroups can be added to GAP dependencies/external libraries, just like GMP---but this is another story, I don't know whether this was ever considered)

Does this sound reasonable?

**Comment by james-d-mitchell** [comment]
Yes, that sounds reasonable. I'd still like the existing checks to remain in case the internal version of `libsemigroups` is the selected one, for the reasons mentioned above. 

About including `libsemigroups` as a dependency of GAP, I doubt that this would be a popular idea, since `libsemigroups` requires a more modern compiler than that currently required by GAP, and is only used by a single package. It seems to me that keeping things self-contained in the Semigroups package is still the best approach.

**Comment by dimpase** [comment]
If someone wants to experiment with a different libsemigroups version, then it's best to install it out of the tree of semigroup - and in this case the convoluted checks for version are not needed. 

I also wan't to get rid of `src/` part of the include path for libsemigroups headers - as `./configure --prefix=foo` installs libsemigroups headers in `foo/include`, without any `src/` bit, and as even with libsemigroups provided as a nested subpackage its configure script is run anyway, it does not look like an obstacle.

**Comment by james-d-mitchell** [comment]
> If someone wants to experiment with a different libsemigroups version, then it's best to install it out of the tree of semigroup - and in this case the convoluted checks for version are not needed.

Maybe that's the case, but I still want there to be some checks on the version of the internal copy of libsemigroups.  This was explicitly requested at some point by some users, and is very useful to us when introducing new contributors to the package. I'm not that concerned about how the checks are performed, only that they exist. 

> I also wan't to get rid of src/ part of the include path for libsemigroups headers - as ./configure --prefix=foo installs libsemigroups headers in foo/include, without any src/ bit, and as even with libsemigroups provided as a nested subpackage its configure script is run anyway, it does not look like an obstacle.

Good idea, I'll be happy to make this change.

**Comment by dimpase** [comment]
Why is the internal libsemigroups not a git submodule? If it were it would simplify things, e.g. one could get rid of `prerequisites.sh` then...

**Comment by james-d-mitchell** [comment]
I never thought of using submodules, is the reason, and now that I am googling it, it seems that "git submodules are universally derided..." which makes me think it isn't a good idea.

**Comment by james-d-mitchell** [comment]
Just for reference PR #584 is an attempt to address this issue.
